# Generated by Django 5.0.4 on 2024-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NONE', max_length=200)),
                ('Price', models.CharField(default='NONE', max_length=200)),
                ('one_hr', models.CharField(default='NONE', max_length=200)),
                ('twenty_four_hr', models.CharField(default='NONE', max_length=200)),
                ('seven_days_hr', models.CharField(default='NONE', max_length=200)),
                ('market_cap', models.CharField(default='NONE', max_length=200)),
                ('volume', models.CharField(default='NONE', max_length=200)),
                ('circulating_supply', models.CharField(default='NONE', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
