# Generated by Django 5.0.4 on 2024-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='Name',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
    ]
